### ISSUE TITLE
Great library

### ISSUE THREAD

**Issue by SkippyZA** [asm89/Rx.PHP#19]
Yo man, just want to say thanks for the awesome library.

**Comment by Ocramius** [comment]
Closing as non-issue, but still poke @asm89 ;-)

**Comment by asm89** [comment]
@Ocramius I keep forgetting you still have access to this repo?! :package: 

Anyway, thanks @SkippyZA. Appreciate you reaching out. :)

**Comment by Ocramius** [comment]
> @Ocramius I keep forgetting you still have access to this repo?! :P

I'm everywhere!
