### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by davidwdan** [asm89/Rx.PHP#24]
The following code will cause php to seg fault:

```php
$observable = new Rx\Observable\ArrayObservable(range(1, 10000));
$observable->subscribe(new \Rx\Observer\CallbackObserver());
```
I'm guessing that this has something to do with the recursive actions in the `ImmediateScheduler` blowing the stack, because it works fine with the `VirtualTimeScheduler`.

**Comment by Ocramius** [comment]
Any specific PHP version? Can a test be created to check this?

**Comment by asm89** [comment]
Yeah, this is most certainly the `ImmediateScheduler` which doesn't use any trampolining and will blow up the stack. We should fix that.

**Comment by davidwdan** [comment]
@Ocramius  All versions of PHP 5.5 - 7 on OSX (10.11.1) and Linux (Centos 6.5)
