### ISSUE TITLE
Implement Your Own Operators

### ISSUE THREAD

**Issue by davidwdan** [asm89/Rx.PHP#5]
With the current version of Rx.PHP, if you want to implement a custom operator, you need to add it to `BaseObservable`.

I propose that we take a page from RxJava and add a `lift` operator, which would allow custom operators to be added to the chain.

For Example:

```PHP

$observable = new Rx\Observable\ArrayObservable(array(21, 21, 42));
$observable
    ->select(function($elem) { return $elem * 2; })
    ->lift(new DistinctUntilChangedOperator())
    ->subscribe($stdoutObserver);
    
```

I've been working on an implementation of this here: https://github.com/davidwdan/Rx.PHP/compare/master...operators?diff=unified&name=operators

It includes the `lift` operator along with `tap`, `never` and `distinctUntilChanged`.

If this is a direction you're interested in going, let me know and I'll create PRs.

**Comment by asm89** [comment]
Shipped. :+1:
