### ISSUE TITLE
Supported PHP versions

### ISSUE THREAD

**Issue by asm89** [asm89/Rx.PHP#7]
Rx.PHP currently supports PHP 5.3. https://github.com/asm89/Rx.PHP/pull/6 changes the requirement to PHP 5.4, but that version is already EOL (http://php.net/eol.php).

How about raising the minimal supported version to either 5.5 or 5.6 and up?

cc @davidwdan @cboden @mbonneau @Ocramius

**Comment by Ocramius** [comment]
@asm89 given the power of the splat operator in 5.6 (especially for functional approaches), I strongly suggest going there.

5.5 bump is a no-brainer: there is NO NEED to support 5.4 or 5.3, just please tag a version before you do that bump.

**Comment by Ocramius** [comment]
Also, maybe start creating milestones? :D

**Comment by mbonneau** [comment]
:+1:

**Comment by asm89** [comment]
@Ocramius Latest release contained all currently relevant commits on master, so we should be good there.

Bumping to 5.5 makes sense indeed. I'm mostly in doubt about going to 5.6. I'm not a big fan of a non type checked splat operator, but `use function` can be nice too.

Given that 5.5 is still officially supported, let's start there for now.

**Comment by asm89** [comment]
Done. See https://github.com/asm89/Rx.PHP/commit/52d83053a0d24e1b5d33d6ae72b4648927d59241.
